# config.yaml

data_dir: sra_data

subdirs:
  lists: sra_lists
  output: sra_files
  logs: logs
  fastq: fastq_files
  split_fastq: split_fastq_files
  star: star

logs:
  csv: csv_logs
  python: python_logs

star:
  genome_dir: genome_ref
  star_output: star_output